config:
  install_tree: $COMPILERS_HOME/install
  source_cache: $COMPILERS_HOME/.cache
  module_roots:
    tcl: $COMPILERS_HOME/modules/tcl
    lmod: $COMPILERS_HOME/modules/lmod
  build_stage:
    - $tempdir
    - $COMPILERS_HOME/.stage
  install_path_scheme: '${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}'
